tomcat:
  access-log-enabled: false
  protocol-header: x-forwarded-proto
  remote-ip-header: x-forwarded-for

spring:
  #  devtools:
  #    restart.enabled: true
  profiles:
    active: dev
    include: ["shiro"]
  application:
    name: crops

  autoconfigure:
    exclude:
    - org.activiti.spring.boot.SecurityAutoConfiguration
    - org.activiti.spring.boot.JpaProcessEngineAutoConfiguration
    - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    - com.vekai.urule.autoconfigure.URuleAutoConfiguration
    - com.vekai.ureport.autoconfigure.UReportAutoConfiguration
    - org.apache.shiro.spring.boot.autoconfigure.ShiroAnnotationProcessorAutoConfiguration

  mvc:
    favicon.enabled: false
    dispatch-options-request: true
    throw-exception-if-no-handler-found: true
  aop:
    auto: true
    proxy-target-class: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #时间格式化
    time-zone: Asia/Chongqing #时区设置
  activiti:
    checkProcessDefinitions: false
    asyncExecutorEnabled: false
  messages:
    basename: /i18n/messages

  batch:
    job:
      names: job1,job2 #启动时要执行的Job，默认执行全部Job
      enabled: false #是否自动执行定义的Job，默认是
    initializer:
      enabled: false #是否初始化Spring Batch的数据库，默认为是

  ##############################
  # 以下是配置不同的模板引擎
  ##############################
  #    Default Extensions are:
  #    *.html - Thymeleaf
  #    *.tpl - Groovy
  #    *.ftl - Freemarker
  #    *.vm - Velocity

  freemarker:
    cache: false
    template-loader-path: ["classpath:/templates/","classpath:/webapp/"]
    prefer-file-system-access: false  #不使用文件系统优先，而使用classpath下的资源文件优先，解决打jar包运行后，出现的异常问题
    allow-request-override: false     #指定HttpServletRequest的属性是否可以覆盖controller的model的同名项
    check-template-location: true     #check-template-location
    charset: UTF-8
    content-type: text/html
    #request/session==true请求和会话属性都被复制到模板的属性集中，此时spring必须设置为true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    request-context-attribute: request
    prefix:
    suffix: .ftl
    classic_compatible: true

  datasource:
    druid:
      initial-size: 10
      max-active: 30
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 25
      filters: stat,wall,slf4j  #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true #合并多个DruidDataSource的监控数据
      StatViewServlet:
        loginUsername: druid
        loginPassword: druid

mybatis:
  configuration:
    map-underscore-to-camel-case: true

#日志配置
logging:
  config: classpath:logback.xml


management:
  context-path: /actuator-manage
  security:
    enabled: false  #否则actuator的监控会报401


security:
  basic:
    enable: false
  ignored: /**

#Fisok的相关配置信息
com.vekai:
  base:
    cache: Memory #Memory,EHCache,Memcached,Redis,MongoDB
    devBaseDir: ${projectRoot}/crops/src/main/resources
    dictDataClasspath: repo/dict
  search:
    directory-mode: Disk
  common:
    file-storage-root: /data/crops #图片附件等文件保存基准路径地址
    file-hist-storage-root: /data/crops/file-historic
    temporary-storage: /data/crops/temporary
  appframe:
    temporary-batch-storage:/data/crops/batch/temporary
  office:
    page-office:
      enable: false
      license-path: /data/crops/pageoffice/license/
      staticResourceUrl: /office/pageoffice/static
  dataform:
    devBaseDir: ${projectRoot}/crops/src/main/resources
    dataformDataClasspath: repo/dataform
    dataFormMapperType: json
    must-touch-fields:
      #      "\\w+\\-\\w+": "createdBy,createdTime,updatedBy,updatedTime" #对所有的查询，如果显示模板上没有这几个属性，自动补上去
      "demo\\-\\w+": "createdBy,createdTime,updatedBy,updatedTime" #对所有的查询，如果显示模板上没有这几个属性，自动补上去
  auth:
    authzFilterEnabled: false
    enableHashPwd: true
    accessControlStrategy:
      anon: ["/", "/ping/*","/nop","/base/profile.js","/base/global-profile.js","/office/pageoffice/**","/showcase/pageoffice/**","/contract/**","/manageReport/**",
             "/**/*.gif","/**/*.png","/**/*.jpeg","/**/*.jpg",
             "/**/*.json", "/**/*.html", "/**/*.ttf", "/**/*.woff",
             "/**/*.js","/**/*.json","/**/*.css","/**/*.less",  "/**/*.ico","/**/*.svg","/pdfjs-1.7.225/**",
             "/editor-app/**","/workflow/design/**",
             "/icon/**", "/devtool/*Json", "/druid/**",
             "/common/FileOperateController/show**File/**","/favicon.ico","/swagger-resources/**","/v2/api-docs",
             "/wsdemo",
             "/wsdemo/*","/comn/file/getCustomer","/file/etl/*","/api/*/*","/api/network/getBigImgById/*",
      ]
      authc: /**
    shiro:
      login-url: "/logon"             #登录地址
      success-url: "/"                #登录成功地址
      unauthorized-url: "/403"        #未授权地址
    audit:      #数据操作审计
      enable: true  #开启审计
      disable-tables: ["FOWK_TIMER"]  #直接不需要审计的表
      igonre-columns: ["REVISION","CREATED_BY","CREATED_TIME","UPDATED_BY","UPDATED_TIME"]  #这五个字段不审计变化
      action-setting:
        "BX_ORDER_INFO": "INSERT,UPDATE"
  #        "[\\w+|CUST_\\w+]": "UPDATE,DELETE" #使用正则表达式匹配，目前需要审计的表以及运作，这个表达式审计所有的数据表
  ##        "CUST_\\w+|IVST_\\w+":"INSERT,UPDATE,DELETE" #审计客户模块以及项目模块的数据表
  sql:
    serial-no:
      generator-map:
        "com.vekai.crops.customer.entity.CustomerPO.custId": "DEFAULT"
        "com.vekai.crops.workflow.entity.WorkflowProcess.procId": "DEFAULT"
        "com.vekai.crops.workflow.entity.WorkflowTask.taskId": "DEFAULT"
        "com.vekai.crops.workflow.entity.WorkflowComment.commentId": "DEFAULT"
        "com.vekai.crops.invest.loan.entity.IvstPlanLoanPO.loanId": "DEFAULT"
      template-map:
        "com.vekai.crops.customer.entity.CustomerPO.custId": "KH000000"
        "com.vekai.crops.workflow.entity.WorkflowProcess.procId": "L000000000"
        "com.vekai.crops.workflow.entity.WorkflowTask.taskId": "T000000000"
        "com.vekai.crops.workflow.entity.WorkflowComment.commentId": "C000000000"
  workflow:
    handler-mapping:
      PersonalLoan: ["com.vekai.workflow.handler.impl.WorkflowDBProcHandler","com.vekai.crops.obiz.application.handler.ApplicationWorkflowHandler"]
      EntCreditLoan: ["com.vekai.workflow.handler.impl.WorkflowDBProcHandler","com.vekai.crops.obiz.application.handler.ApplicationWorkflowHandler"]

    #规则引擎属性配置
    urule:
      sample1: abcdef1

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    client-etl:
      path: /etl/**
      #      url: http://127.0.0.1:8082/
      serviceId: crops-etl

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000