#server: { port: 8080,contextPath: /crops ,sessionTimeout: 30}
server:
  port: 8080
  servlet:
    context-path: /crops
    session:
      timeout: "30m"

eureka:
  client:
    register-with-eureka: false #不向注册中心注册自己，启动服务注册,如果不做集群，高可用，则关闭它
    fetch-registry: false       #由于注册中心职责就是维护服务实例，它并不需要去检索服务，设置成false
    service-url:
      defaultZone: "http://127.0.0.1:1111/rsc/eureka/"

  instance:
    appname: "${spring.application.name}"
    instance-id: "${spring.application.name}:${server.port}"
    prefer-ip-address: true                       # 设置微服务调用地址为IP优先（缺省为false）
    lease-renewal-interval-in-seconds: 5          # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15      # 发呆时间，即服务续约到期时间（缺省为90s）

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    url: jdbc:db2://111.229.64.141:50000/mydb:currentSchema=DB2INST1;
    username: db2inst1
    password: db2inst1-pwd

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: a123456x
    timeout: 1000
#    host: 192.168.64.146
#    port: 32068
#    password: sde78xfel0
#    timeout: 1000

    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 1000


endpoints:
  sensitive: false
  cors:
    allowedOrigins: "*"
    allowedHeaders: "*"
    allowCredentials: true
    exposedHeaders: WWW-Authenticate

debug: true

com.vekai:
  base:
    cache: Memory #Memory,EHCache,Memcached,Redis,MongoDB
  batch:
    logdao: Redis #DataTable,Redis
  auth:
    enableJwtReplaceSession: false
  runtime:
    corsEnable: true
  sql:
    sql-dialect-type: DB2

#URule的设置
urule:
  ##文件存储的方式
  #  repository:
  #      dir: /Users/cytsir/Documents/ws-set/ws-rober/vekai-cabin/vekai-urule/src/test/resources/repo
  #      dir: vekai-showcase/src/main/resources/repo/rules #相对路径的方式，要确保这个目录的存在
  #数据库存储的方式
  repository:
    datasourcename: dataSource
    databasetype: mysql
  welcomePage: welcomeHome
  console:
    title: "规则引擎"

#UReport报表引擎的设置
ureport:
  #  fileStoreDir: /Users/cytsir/Documents/ws-set/ws-rober/vekai-cabin/vekai-ureport/src/test/repo1
  #  fileStoreDir: vekai-ureport/src/test/repo1
  fileStoreDir: reportfiles
  disableFileProvider: false
  disableHttpSessionReportCache: false
  debug: true

com:
  vekai:
    crops:
      enable-websocker: true