DELETE FROM ACT_HI_ATTACHMENT;
DELETE FROM ACT_HI_COMMENT;
DELETE FROM ACT_HI_DETAIL;
DELETE FROM ACT_HI_ACTINST;
DELETE FROM ACT_HI_IDENTITYLINK;
DELETE FROM ACT_HI_PROCINST;
DELETE FROM ACT_HI_TASKINST;
DELETE FROM ACT_HI_VARINST;
DELETE FROM ACT_RU_IDENTITYLINK;
DELETE FROM ACT_RU_TASK;
DELETE FROM ACT_RU_VARIABLE;
DELETE FROM ACT_RU_EXECUTION WHERE PARENT_ID_ IS NOT NULL AND IS_SCOPE_=0;
DELETE FROM ACT_RU_EXECUTION WHERE PARENT_ID_ IS NOT NULL AND IS_SCOPE_=1;
DELETE FROM ACT_RU_EXECUTION;


TRUNCATE TABLE WKFL_CANDIDATE;
TRUNCATE TABLE WKFL_COMMENT;
TRUNCATE TABLE WKFL_COMMENT_HIST;
TRUNCATE TABLE WKFL_PROC;
TRUNCATE TABLE WKFL_TASK;
TRUNCATE TABLE WKFL_TASK_HIST;