CREATE OR REPLACE VIEW ACT_ID_USER AS
SELECT
	AUTH_USER.ID AS ID_,
	AUTH_USER.REVISION AS REV_,
	AUTH_USER.NAME AS FIRST_,
	'' AS LAST_,
	AUTH_USER.EMAIL AS EMAIL_,
	'' AS PWD_,
	'' AS PICTURE_ID_
FROM
	AUTH_USER;


CREATE OR REPLACE VIEW ACT_ID_GROUP AS
SELECT
	AUTH_ROLE.ID AS ID_,
	AUTH_ROLE.REVISION AS REV_,
	AUTH_ROLE.NAME AS NAME_,
	'' AS TYPE_
FROM
	AUTH_ROLE;

CREATE OR REPLACE VIEW ACT_ID_MEMBERSHIP AS
SELECT
	AUTH_USER_ROLE.USER_ID AS USER_ID_,
	AUTH_USER_ROLE.ROLE_ID AS GROUP_ID_
FROM
	AUTH_USER_ROLE WHERE EXISTS(SELECT 1 FROM AUTH_ROLE WHERE AUTH_ROLE.IN_WORK_FLOW='Y' AND AUTH_ROLE.ID=AUTH_USER_ROLE.ROLE_ID);