DROP TABLE IF EXISTS  wkfl_candidate;
CREATE TABLE wkfl_candidate (
  TASK_ID varchar(32) DEFAULT NULL COMMENT '任务标识号',
  CANDIDATE_ID varchar(32) NOT NULL COMMENT '标识号',
  CANDIDATE_TYPE varchar(32) DEFAULT NULL COMMENT '候选类型',
  USER_ID varchar(32) DEFAULT NULL COMMENT '关联用户号',
  SOURCE_TYPE varchar(32) DEFAULT NULL COMMENT '来源类型,流程正常提交，授权添加',
  SCOPE_TYPE varchar(32) DEFAULT NULL COMMENT '范围限制类型,角色；角色+机构；团队；',
  SCOPE_ROLE_ID varchar(32) DEFAULT NULL COMMENT '范围角色号',
  SCOPE_ORG_ID varchar(32) DEFAULT NULL COMMENT '范围机构号',
  SCOPE_TEAM_ID varchar(32) DEFAULT NULL COMMENT '范围团队号',
  REVISION int(11) DEFAULT NULL COMMENT '乐观锁版本',
  CREATED_BY varchar(32) DEFAULT NULL COMMENT '创建人',
  CREATED_TIME datetime DEFAULT NULL COMMENT '创建时间',
  UPDATED_BY varchar(32) DEFAULT NULL COMMENT '更新人',
  UPDATED_TIME datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (CANDIDATE_ID)
) COMMENT='任务关联候选人信息';

DROP TABLE IF EXISTS  wkfl_comment;
CREATE TABLE wkfl_comment (
  PROC_ID varchar(32) DEFAULT NULL COMMENT '流程实例标识号',
  TASK_ID varchar(32) DEFAULT NULL COMMENT '任务标识号',
  COMMENT_ID varchar(32) NOT NULL COMMENT '意见标识号',
  COMMENT_INST_ID varchar(32) DEFAULT NULL COMMENT '意见引擎实例号',
  COMMENT_TYPE varchar(32) DEFAULT NULL COMMENT '意见类型,处理意见;被征求的意见；授权处理的意见',
  MESSAGE varchar(3000) DEFAULT NULL COMMENT '意见内容',
  USER_ID varchar(32) DEFAULT NULL COMMENT '意见发表人',
  ACTION varchar(180) DEFAULT NULL COMMENT '处理意见,同意，保留意见；拒绝',
  ACTION_INTRO varchar(900) DEFAULT NULL COMMENT '处理结果介绍',
  REVISION int(11) DEFAULT NULL COMMENT '乐观锁版本',
  CREATED_BY varchar(32) DEFAULT NULL COMMENT '创建人',
  CREATED_TIME datetime DEFAULT NULL COMMENT '创建时间',
  UPDATED_BY varchar(32) DEFAULT NULL COMMENT '更新人',
  UPDATED_TIME datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (COMMENT_ID)
) COMMENT='流程意见';

DROP TABLE IF EXISTS  wkfl_comment_hist;
CREATE TABLE wkfl_comment_hist (
  PROC_ID varchar(32) DEFAULT NULL COMMENT '流程实例标识号',
  TASK_ID varchar(32) DEFAULT NULL COMMENT '任务标识号',
  COMMENT_ID varchar(32) NOT NULL COMMENT '意见标识号',
  COMMENT_INST_ID varchar(32) DEFAULT NULL COMMENT '意见引擎实例号',
  COMMENT_TYPE varchar(32) DEFAULT NULL COMMENT '意见类型,处理意见;被征求的意见；授权处理的意见',
  MESSAGE varchar(3000) DEFAULT NULL COMMENT '意见内容',
  USER_ID varchar(32) DEFAULT NULL COMMENT '意见发表人',
  ACTION varchar(180) DEFAULT NULL COMMENT '处理意见,同意，保留意见；拒绝',
  ACTION_INTRO varchar(900) DEFAULT NULL COMMENT '处理结果介绍',
  REVISION int(11) DEFAULT NULL COMMENT '乐观锁版本',
  CREATED_BY varchar(32) DEFAULT NULL COMMENT '创建人',
  CREATED_TIME datetime DEFAULT NULL COMMENT '创建时间',
  UPDATED_BY varchar(32) DEFAULT NULL COMMENT '更新人',
  UPDATED_TIME datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (COMMENT_ID)
) COMMENT='流程意见';

DROP TABLE IF EXISTS  wkfl_conf_bom;
CREATE TABLE wkfl_conf_bom (
  BOM_ID varchar(32) NOT NULL COMMENT '流程业务参数ID',
  PROC_DEF_KEY varchar(180) NOT NULL COMMENT '流程定义KEY',
  TYPE_ varchar(150) DEFAULT NULL COMMENT '参数类型:业务参数,原生参数',
  NAME varchar(150) DEFAULT NULL COMMENT '参数名称',
  VALUE_ varchar(150) DEFAULT NULL COMMENT '参数内容:参数表达式等',
  REVISION int(11) DEFAULT NULL COMMENT '乐观锁',
  CREATED_BY varchar(32) DEFAULT NULL COMMENT '创建人',
  CREATED_TIME datetime DEFAULT NULL COMMENT '创建时间',
  UPDATED_BY varchar(32) DEFAULT NULL COMMENT '更新人',
  UPDATED_TIME datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (BOM_ID,PROC_DEF_KEY) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='流程业务参数对象表';

DROP TABLE IF EXISTS  wkfl_conf_resource;
CREATE TABLE wkfl_conf_resource (
  RESOURCE_ID varchar(32) NOT NULL COMMENT '资源ID',
  PROC_DEF_KEY varchar(180) NOT NULL COMMENT '流程定义KEY',
  SORT_CODE varchar(32) DEFAULT NULL COMMENT '排序号',
  TYPE_ varchar(150) DEFAULT NULL COMMENT '资源类型:按钮,超链接,信息块',
  NAME varchar(150) DEFAULT NULL COMMENT '资源名称',
  ACTION varchar(150) DEFAULT NULL COMMENT '资源内容',
  ACTION_HINT varchar(150) DEFAULT NULL COMMENT '动作示意',
  ICON_ varchar(150) DEFAULT NULL COMMENT '图标',
  STYLE_ varchar(150) DEFAULT NULL COMMENT '样式',
  IS_EXPANDED varchar(8) DEFAULT NULL COMMENT '信息块默认是否展开',
  IS_INST_RESOURCE varchar(8) DEFAULT NULL COMMENT '实例级资源',
  RESOURCE_LOCATION varchar(32) DEFAULT NULL COMMENT '资源所在区域',
  REVISION int(11) DEFAULT NULL COMMENT '乐观锁',
  CREATED_BY varchar(32) DEFAULT NULL COMMENT '创建人',
  CREATED_TIME datetime DEFAULT NULL COMMENT '创建时间',
  UPDATED_BY varchar(32) DEFAULT NULL COMMENT '更新人',
  UPDATED_TIME datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (RESOURCE_ID,PROC_DEF_KEY) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='流程资源表';

DROP TABLE IF EXISTS  wkfl_lite_form;
CREATE TABLE wkfl_lite_form (
  FORM_ID varchar(32) NOT NULL COMMENT '审批表单ID',
  NAME varchar(150) DEFAULT NULL COMMENT '审批表单名称',
  CATEGORY varchar(150) DEFAULT NULL COMMENT '审批表单分类',
  PROC_DEF_KEY varchar(180) NOT NULL COMMENT '流程定义KEY',
  REVISION int(11) DEFAULT NULL COMMENT '乐观锁',
  CREATED_BY varchar(32) DEFAULT NULL COMMENT '创建人',
  CREATED_TIME datetime DEFAULT NULL COMMENT '创建时间',
  UPDATED_BY varchar(32) DEFAULT NULL COMMENT '更新人',
  UPDATED_TIME datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (FORM_ID) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='简式流审批表单';

DROP TABLE IF EXISTS  wkfl_lite_resource;
CREATE TABLE wkfl_lite_resource (
  RESOURCE_ID varchar(32) NOT NULL COMMENT '资源ID',
  PROC_DEF_KEY varchar(180) NOT NULL COMMENT '流程定义KEY',
  SORT_CODE varchar(32) DEFAULT NULL COMMENT '排序号',
  TYPE_ varchar(150) DEFAULT NULL COMMENT '资源类型:按钮,超链接,信息块',
  NAME varchar(150) DEFAULT NULL COMMENT '资源名称',
  ACTION varchar(150) DEFAULT NULL COMMENT '资源内容',
  ACTION_HINT varchar(150) DEFAULT NULL COMMENT '动作示意',
  ICON_ varchar(150) DEFAULT NULL COMMENT '图标',
  STYLE_ varchar(150) DEFAULT NULL COMMENT '样式',
  IS_EXPANDED varchar(8) DEFAULT NULL COMMENT '信息块默认是否展开',
  REVISION int(11) DEFAULT NULL COMMENT '乐观锁',
  CREATED_BY varchar(32) DEFAULT NULL COMMENT '创建人',
  CREATED_TIME datetime DEFAULT NULL COMMENT '创建时间',
  UPDATED_BY varchar(32) DEFAULT NULL COMMENT '更新人',
  UPDATED_TIME datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (PROC_DEF_KEY,RESOURCE_ID) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='简式流程资源表';

DROP TABLE IF EXISTS  wkfl_lite_template;
CREATE TABLE wkfl_lite_template (
  TEMPLATE_ID varchar(32) NOT NULL COMMENT '模板ID',
  CATEGORY varchar(150) DEFAULT NULL COMMENT '模板分类',
  NAME varchar(150) DEFAULT NULL COMMENT '模板名称',
  DEF_EXPLICIT varchar(3000) DEFAULT NULL COMMENT '隐式简式流程定义',
  DEF_IMPLICIT varchar(3000) DEFAULT NULL COMMENT '显式简式流程定义',
  REVISION int(11) DEFAULT NULL COMMENT '乐观锁',
  CREATED_BY varchar(32) DEFAULT NULL COMMENT '创建人',
  CREATED_TIME datetime DEFAULT NULL COMMENT '创建时间',
  UPDATED_BY varchar(32) DEFAULT NULL COMMENT '更新人',
  UPDATED_TIME datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (TEMPLATE_ID) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='简式流程预设模板表';

DROP TABLE IF EXISTS  wkfl_solicit;
CREATE TABLE wkfl_solicit (
  PROC_ID varchar(32) DEFAULT NULL,
  TASK_ID varchar(32) DEFAULT NULL COMMENT '任务标识号',
  SOLICIT_ID varchar(32) NOT NULL COMMENT '标识号',
  SOLICIT_SUMMARY varchar(900) DEFAULT NULL COMMENT '征求说明;什么人在什么阶段征求认谁的意见',
  SOLICITOR varchar(32) DEFAULT NULL COMMENT '征求人',
  SOLICIT_COMMENT varchar(3000) DEFAULT NULL COMMENT '征求意见',
  ASK_FOR varchar(32) DEFAULT NULL COMMENT '被征求人',
  REPLY_COMMENT varchar(3000) DEFAULT NULL COMMENT '反馈意见',
  REVISION int(11) DEFAULT NULL COMMENT '乐观锁版本',
  CREATED_BY varchar(32) DEFAULT NULL COMMENT '创建人',
  CREATED_TIME datetime DEFAULT NULL COMMENT '创建时间',
  UPDATED_BY varchar(32) DEFAULT NULL COMMENT '更新人',
  UPDATED_TIME datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (SOLICIT_ID) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务意见征求';

DROP TABLE IF EXISTS  wkfl_proc;
CREATE TABLE wkfl_proc (
  PROC_ID varchar(32) NOT NULL COMMENT '流程实例标识号',
  OBJECT_TYPE varchar(32) DEFAULT NULL COMMENT '关联对象类型',
  OBJECT_ID varchar(32) DEFAULT NULL COMMENT '关联对象标识号',
  PROC_INST_ID varchar(32) DEFAULT NULL COMMENT '流程引擎实例号',
  PROC_DEF_KEY varchar(180) DEFAULT NULL COMMENT '流程定义关键字',
  PROC_DEF_ID varchar(64) DEFAULT NULL COMMENT '流程定义ID',
  PROC_NAME varchar(150) DEFAULT NULL COMMENT '流程名称',
  SUMMARY varchar(180) DEFAULT NULL COMMENT '流程实例描述',
  SPONSOR varchar(32) DEFAULT NULL COMMENT '发起人',
  START_TIME datetime DEFAULT NULL COMMENT '启动时间',
  FINISH_TIME datetime DEFAULT NULL COMMENT '结束时间',
  STATUS varchar(32) DEFAULT NULL COMMENT '流程状态；发起,审批中,退回,驳回,通过,拒绝,作废',
  LAST_TASK_JSON varchar(2000) DEFAULT NULL COMMENT '当前任务信息JSON',
  LAST_TASK_DESC varchar(2000) DEFAULT NULL COMMENT '当前任务描述',
  LAST_ASSIGNEE_DESC varchar(1000) DEFAULT NULL COMMENT '当前受理人描述',
  FIRST_COMMENT varchar(3000) DEFAULT NULL COMMENT '首个意见',
  LAST_COMMENT varchar(3000) DEFAULT NULL COMMENT '最新意见',
  PAGE_PARAM varchar(900) DEFAULT NULL COMMENT '页面参数',
  FLOW_TYPE varchar(32) DEFAULT NULL COMMENT '流程类型,FULL:完整的流程引擎(基于activiti)的，LITE:简式流程',
  LITE_FLOW_DEF varchar(3000) DEFAULT NULL COMMENT '简式流程定义数据',
  HANDLER varchar(180) DEFAULT NULL COMMENT '扩展处理类',
  CUR_MAX_DEPTH varchar(32) DEFAULT NULL COMMENT '当前节点最深路径长度',
  MAX_DEPTH varchar(32) DEFAULT NULL COMMENT '所有节点最深路径长度',
  REVISION int(11) DEFAULT NULL COMMENT '乐观锁版本',
  CREATED_BY varchar(32) DEFAULT NULL COMMENT '创建人',
  CREATED_TIME datetime DEFAULT NULL COMMENT '创建时间',
  UPDATED_BY varchar(32) DEFAULT NULL COMMENT '更新人',
  UPDATED_TIME datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (PROC_ID) USING BTREE
) COMMENT='流程业务实例';

DROP TABLE IF EXISTS  wkfl_solicit_hist;
CREATE TABLE wkfl_solicit_hist (
  PROC_ID varchar(32) NOT NULL,
  TASK_ID varchar(32) DEFAULT NULL COMMENT '任务标识号',
  SOLICIT_ID varchar(32) NOT NULL COMMENT '标识号',
  SOLICIT_SUMMARY varchar(900) DEFAULT NULL COMMENT '征求说明;什么人在什么阶段征求认谁的意见',
  SOLICITOR varchar(32) DEFAULT NULL COMMENT '征求人',
  SOLICIT_COMMENT varchar(3000) DEFAULT NULL COMMENT '征求意见',
  ASK_FOR varchar(32) DEFAULT NULL COMMENT '被征求人',
  REPLY_COMMENT varchar(3000) DEFAULT NULL COMMENT '反馈意见',
  REVISION int(11) DEFAULT NULL COMMENT '乐观锁版本',
  CREATED_BY varchar(32) DEFAULT NULL COMMENT '创建人',
  CREATED_TIME datetime DEFAULT NULL COMMENT '创建时间',
  UPDATED_BY varchar(32) DEFAULT NULL COMMENT '更新人',
  UPDATED_TIME datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (SOLICIT_ID) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务意见征求';

DROP TABLE IF EXISTS  wkfl_task_hist;
CREATE TABLE wkfl_task_hist (
  PROC_ID varchar(32) NOT NULL COMMENT '流程实例标识号',
  TASK_ID varchar(32) NOT NULL COMMENT '任务标识号',
  TASK_INST_ID varchar(32) DEFAULT NULL COMMENT '任务引擎实例号',
  TASK_DEF_KEY varchar(180) DEFAULT NULL COMMENT '任务定义KEY',
  TASK_NAME varchar(150) DEFAULT NULL COMMENT '任务名称',
  OWNER varchar(32) DEFAULT NULL COMMENT '任务持有人',
  ASSIGNEE varchar(32) DEFAULT NULL COMMENT '任务办理人',
  IS_CONCURRENT varchar(1) DEFAULT NULL,
  ARRIVAL_TIME datetime DEFAULT NULL COMMENT '任务到达时间',
  FINISH_TIME datetime DEFAULT NULL COMMENT '任务结束时间',
  FINISH_TYPE varchar(32) DEFAULT NULL COMMENT '任务终结类型,正常提交，退回',
  REVISION int(11) DEFAULT NULL COMMENT '乐观锁版本',
  CREATED_BY varchar(32) DEFAULT NULL COMMENT '创建人',
  CREATED_TIME datetime DEFAULT NULL COMMENT '创建时间',
  UPDATED_BY varchar(32) DEFAULT NULL COMMENT '更新人',
  UPDATED_TIME datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (TASK_ID) USING BTREE
) COMMENT='流程任务';

DROP TABLE IF EXISTS  wkfl_task;
CREATE TABLE wkfl_task (
  PROC_ID varchar(32) NOT NULL COMMENT '流程实例标识号',
  TASK_ID varchar(32) NOT NULL COMMENT '任务标识号',
  TASK_INST_ID varchar(32) DEFAULT NULL COMMENT '任务引擎实例号',
  TASK_DEF_KEY varchar(180) DEFAULT NULL COMMENT '任务定义KEY',
  TASK_NAME varchar(150) DEFAULT NULL COMMENT '任务名称',
  OWNER varchar(32) DEFAULT NULL COMMENT '任务持有人',
  ASSIGNEE varchar(32) DEFAULT NULL COMMENT '任务办理人',
  IS_CONCURRENT varchar(1) DEFAULT NULL,
  ARRIVAL_TIME datetime DEFAULT NULL COMMENT '任务到达时间',
  FINISH_TIME datetime DEFAULT NULL COMMENT '任务结束时间',
  FINISH_TYPE varchar(32) DEFAULT NULL COMMENT '任务终结类型,正常提交，退回',
  REVISION int(11) DEFAULT NULL COMMENT '乐观锁版本',
  CREATED_BY varchar(32) DEFAULT NULL COMMENT '创建人',
  CREATED_TIME datetime DEFAULT NULL COMMENT '创建时间',
  UPDATED_BY varchar(32) DEFAULT NULL COMMENT '更新人',
  UPDATED_TIME datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (TASK_ID)
) COMMENT='流程任务';

DROP TABLE IF EXISTS  WKFL_COMMON_COMMENT;
CREATE TABLE WKFL_COMMON_COMMENT(
    ID VARCHAR(32)  COMMENT '主键' ,
    COMMON_COMMENT VARCHAR(1024)  COMMENT '常用语' ,
    HOT_SPOT VARCHAR(32)  COMMENT '热度' ,
    SORT_CODE VARCHAR(32)  COMMENT '排序码' ,
    REVISION INT  COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(32)  COMMENT '创建人' ,
    CREATED_TIME DATETIME  COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)  COMMENT '更新人' ,
    UPDATED_TIME DATETIME  COMMENT '更新时间' ,
    PRIMARY KEY (ID)
) COMMENT = '流程常用意见;'
